import requests
import streamlit as st

st.set_page_config(layout="wide")
st.title("Camera input demo app. Take photo and see it toonified!")

col_left, _, col_right = st.columns([5, 1, 4])

with col_left:
    webcam_photo = st.camera_input(label="")

with col_right:
    if webcam_photo:
        with st.spinner("Processing..."):
            r = requests.post(
                "https://api.deepai.org/api/toonify",
                files={"image": webcam_photo},
                headers={"api-key": st.secrets.api_key},
            )
            st.text("")
            if r.status_code == 200:
                response = r.json()
                st.image(response["output_url"])
                st.caption(
                    "Image generated by [Toonify](https://deepai.org/machine-learning-model/toonify)"
                )
            else:
                st.write(
                    "An error occurred processing your input. Please check your input and try again."
                )
